### ISSUE TITLE
협업 기초 세팅

### ISSUE THREAD

**Issue by jyh071116** [Team-INSERT/IOJ_WEB#1]
### 💡 개요
원활한 협업을 진행하기 위한 깃/깃허브 세팅을 진행할 것입니다.
### ✅ 해야 할 일
- [x] Issue template 생성
- [x] PR template 생성
- [x] commit convention 작성
- [x] CODEOWNERS 작성
- [x] gitflow를 위한 branch 세팅

**Comment by zeroeuni** [comment]
세팅 완료하였습니댜.
